server {
    listen 80;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html;
    
    # Важно! Для маршрутизации в React (чтобы работало обновление страницы)
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    # Перенаправляем запросы к API на наш бэкенд
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
    }
}